Feat/fast withdrawals
tanx-libs/tanx-connector-python pull request #5
Opened 2024-02-29 12:00 UTC by ayush-tanx

2024-02-29 12:00 UTC, ayush-tanx commented
Took a pull from polygon deposits due to utils dependency.

2024-03-01 12:07 UTC, austinjfi commented on src/brineconnector/client.py
> +        body = params_to_dict(loc)
remove this where body/params isn't required

2024-03-01 12:08 UTC, austinjfi commented on src/brineconnector/client.py
> +        print(polygon_config)
remove this

2024-03-04 06:58 UTC, austinjfi commented on src/brineconnector/utils.py
> +    elif type == 'WITHDRAWL':
Typo here. Please test out all cases.

2024-03-04 06:59 UTC, austinjfi commented on src/brineconnector/utils.py
> +        allowed_token = next((token for token in allowed_tokens_for_fast_withdrawl if token == coin), None)
typo here.

2024-03-04 07:02 UTC, austinjfi requested changes
Please have a look.

2024-03-12 06:39 UTC, austinjfi commented on example/withdrawals.py
> +        key_pair = get_stark_key_pair_from_signature(user_signature)
Remove these functions

2024-03-13 19:31 UTC, austinjfi approved these changes
lgtm

2024-03-15 11:59 UTC, merged